food/urls.py
from django.urls import path
from food import views
from recipes.views import index as recipe_index

app_name = 'food'
urlpatterns = [
    path('', recipe_index, name='index'),
    path('ajax/get/getRawFoodMeasurementTypes', views.getRawFoodMeasurementTypes, name="getRawFoodMeasurementTypes")
]

groceries/urls.py
from django.urls import path
from groceries import views
from recipes.views import index as recipe_index

app_name = 'groceries'
urlpatterns = [
    path('', recipe_index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('shoppinglist/', views.shopping_list, name='shoppinglist'),
    path('get_added_grocery/', views.get_added_grocery, name="get_added_grocery"),
    path('delete_grocery/', views.delete_grocery, name="delete_grocery"),
    path('change_amount/', views.change_amount, name="change_amount"),
    path('save_recipe', views.save_recipe, name="save_recipe"),
    path('recipelist/', views.recipes_list, name="recipe_list"),
]

rapid_recipes/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipes import views
from django.conf import settings
from django.conf.urls.static import static

#app_name='rapid'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('recipes/', include('recipes.urls')),

    path('food/', include('food.urls')),
    path('groceries/', include('groceries.urls')),
    path('about/', views.about, name='about'), 
    path('contact/', views.contact, name='contact'),
    path('contact/success', views.success, name='success'), 


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('<slug:recipe_name_slug>/', views.show_recipe, name='show_recipe'),
    path('search', views.search, name='search'),
]

templates/rapidrecipes/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="generator" content="Jekyll v3.8.5">
  <link rel="stylesheet" href="{% static 'stylesheets/styles.css' %}" />
  <script src="https://kit.fontawesome.com/15decd2465.js" crossorigin="anonymous"></script>
  <title>
    Rapid Recipes {% block title_block %} {% endblock %}
  </title>

  <!-- Bootstrap core CSS -->
  <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
  
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.2.0/dist/select2-bootstrap-5-theme.min.css" />

</head>

<body>
  <header>
  {% block filter_block %}
  {% endblock %}
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0ms-auto">
      <a class="navbar-brand p-2" href="{% url 'recipes:index' %}">Rapid Recipes</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="{% url 'recipes:index' %}">Home</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'about' %}">About</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'groceries:logout' %}?next=/rango/">Logout</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'recipes:add_recipe' %}">Add Recipe</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'groceries:shoppinglist' %}">Your Groceries</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'groceries:recipe_list' %}">Your Recipes</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'groceries:register' %}">Register Here</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'groceries:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
      <form class="form-inline my-2 my-lg-0" method=POST action={% url 'recipes:search' %}>
	  
		{% csrf_token %}
		
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name ="search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      </div>
    </nav>
  </header>
  <!-- Load minified jquery (slim does not contain ajax) before content_block is loaded -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <main role="main" class="my-3">
    {% block content_block %}
    {% endblock %}
  </main>

  <!-- Bootstrap core JavaScript -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
  <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
</body>

</html>