food/urls.py
from django.urls import path
from food import views
from recipes.views import index as recipe_index

app_name = 'food'
urlpatterns = [
    path('', recipe_index, name='index'),
    path('ajax/get/getRawFoodMeasurementTypes', views.getRawFoodMeasurementTypes, name="getRawFoodMeasurementTypes")
]

groceries/urls.py
from django.urls import path
from groceries import views
from recipes.views import index as recipe_index

app_name = 'groceries'
urlpatterns = [
    path('', recipe_index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('shoppinglist/', views.shopping_list, name='shoppinglist'),
    path('get_added_grocery/', views.get_added_grocery, name="get_added_grocery"),
    path('delete_grocery/', views.delete_grocery, name="delete_grocery"),
    path('change_amount/', views.change_amount, name="change_amount"),
    path('save_recipe', views.save_recipe, name="save_recipe"),
    path('recipelist/', views.recipes_list, name="recipe_list"),
]

rapid_recipes/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipes import views
from django.conf import settings
from django.conf.urls.static import static

#app_name='rapid'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('recipes/', include('recipes.urls')),

    path('food/', include('food.urls')),
    path('groceries/', include('groceries.urls')),
    path('about/', views.about, name='about'), 
    path('contact/', views.contact, name='contact'),
    path('contact/success', views.success, name='success'), 


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('<slug:recipe_name_slug>/', views.show_recipe, name='show_recipe'),
    path('search', views.search, name='search'),
]

groceries/models.py
from django.db import models
from django.contrib.auth.models import User
from food.models import RawFood, Measurement
from recipes.models import Recipe

class GroceryItem(models.Model):

    AMOUNT_MAX_LENGTH = 50

    rawFood = models.ForeignKey(RawFood, on_delete=models.CASCADE)
    amount = models.CharField(max_length=AMOUNT_MAX_LENGTH)
    available = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    measuredIn = models.ForeignKey(Measurement, on_delete=models.CASCADE)

    def __str__(self):
        return self.rawFood.name

groceries/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

    def clean(self):
        clean_data = super(UserForm, self).clean()
        password = clean_data.get('password')

        if password is not None:
            if len(password) < 6:
                raise forms.ValidationError('Password is too short')

recipes/forms.py
from pickletools import read_uint1
from django import forms
from django.db import models
from django.contrib.auth.models import User
from recipes.models import Instruction, Recipe, Ingredient, Category

class ContactForm(forms.Form):
    firstname = forms.CharField(required=True)
    lastname = forms.CharField(required=True)
    phonenumber = forms.CharField(required=False)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

class FilterForm(forms.Form):
    lunch = forms.BooleanField(label='lunch', required=False)
    dinner = forms.BooleanField(label='dinner', required=False)
    breakfast = forms.BooleanField(label='breakfast', required=False)
    easy = forms.BooleanField(label='easy', required=False)
    medium = forms.BooleanField(label='medium', required=False)
    hard = forms.BooleanField(label='hard', required=False)
    drink = forms.BooleanField(label='drink', required=False)
    vegan = forms.BooleanField(label='vegan', required=False)
    vegetarian = forms.BooleanField(label='vegetarian', required=False)
    beef = forms.BooleanField(label='beef', required=False)
    chicken = forms.BooleanField(label='chicken', required=False)
    fish = forms.BooleanField(label='fish', required=False)
    
    

groceries/views.py
from calendar import c
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from groceries.models import GroceryItem
from recipes.models import Measurement, Recipe
from food.models import RawFood
from django.contrib.auth.models import User
from groceries.forms import UserForm


def register(request):
    registered = False
    context = {'registered': registered}
    if request.method == 'POST':
        user_form = UserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            login(request, user)
            return redirect(reverse('index'))
        else:
            print(user_form.errors)
            context['form'] = user_form
    return render(request,'groceries/register.html', context)
                
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('index'))
            else:
                return HttpResponse("Your account is currently disabled")
        else:
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'groceries/login.html')

@login_required
def user_logout(request):

    logout(request)

    return redirect(reverse('index'))

@login_required
def shopping_list(request):
    context = {'rawFoods' : RawFood.objects.all()}
    context['groceries'] = GroceryItem.objects.filter(user=request.user)
    return render(request, 'groceries/shoppingList.html', context)

@login_required
def recipes_list(request):
    context = {}
    context['recipes'] = Recipe.objects.filter(users=request.user)
    return render(request, 'groceries/recipesList.html', context)

def get_added_grocery(request):
    if request.method == "GET":
        get = request.GET
        user = request.user
        ingredient = get.get("i", None)
        measurement = get.get("m", None)
        amount = get.get("a", None)
        owned = get.get("o", None)
        if owned:
            owned = not (owned == "false")
        else:
            owned = False
        context={}
        try:
            rawFood = RawFood.objects.get(name=ingredient)
            measuredIn = Measurement.objects.get(unit=measurement)
            grocery = GroceryItem.objects.create(rawFood=rawFood,
                                                        amount=amount,
                                                        available=owned,
                                                        user=user,
                                                        measuredIn=measuredIn)[0]
            grocery.save()
            context['groceries'] = GroceryItem.objects.filter(user=request.user)
        except (RawFood.DoesNotExist, Measurement.DoesNotExist) as e:
            context['groceries'] = GroceryItem.objects.filter(user=request.user)
        return render(request, "groceries/table_body.html", context)

def delete_grocery(request):
    if request.method == "GET":
        get = request.GET
        user = request.user
        id = get.get("id", None)
        context = {}
        try:
            GroceryItem.objects.get(id=id, user=user).delete()
            context['groceries'] = GroceryItem.objects.filter(user=request.user)
        except (RawFood.DoesNotExist, Measurement.DoesNotExist) as e:
            context['groceries'] = GroceryItem.objects.filter(user=request.user)
        return render(request, "groceries/table_body.html", context)


def change_amount(request):
    if request.method == "GET":
        get = request.GET
        user = request.user
        id = get.get("id", None)
        amount = get.get("a", None)
        context = {}
        try:
            groceryItem = GroceryItem.objects.get(id=id, user=user)
            groceryItem.amount = amount
            groceryItem.save()
            context['groceries'] = GroceryItem.objects.filter(user=request.user)
        except (RawFood.DoesNotExist, Measurement.DoesNotExist) as e:
            context['groceries'] = GroceryItem.objects.filter(user=request.user)
        return render(request, "groceries/table_body.html", context)


def save_recipe(request):
    if request.is_ajax and request.method == "GET":
        recipe = request.GET.get("recipe_id", None)
        user = request.user
        try:
            recipe = Recipe.objects.get(id=recipe)
            user = User.objects.get(id=user.id)
            recipe.users.add(user)
            recipe.save()
        except (Recipe.DoesNotExist, User.DoesNotExist) as e:
            print("Error")
    return JsonResponse({}, status=200)        

templates/groceries/login.html
{% extends 'rapidrecipes/base.html' %}
{% block content_block %}
<div class="container-fluid my-2">
    <h2>Login</h2>
    <form class="form-signin" role="form" method="post" action=".">
        {% csrf_token %}
        <p>Username*:</p>
        <input type="text" name="username" id="id_username" class="form-control w-25"
        placeholder="Username" required autofocus>
        <p>Password*:</p>
        <input type="password" name="password" id="id_password" class="form-control w-25"
        placeholder="Password" required>
        <p></p>
        <button class="btn btn-lg btn-primary btn-block w-25" type="submit"
        value="Submit">Sign in</button>
    </form>    
</div>
{% endblock %}

templates/groceries/recipesList.html
{% extends 'rapidrecipes/base.html' %}
{% block content_block %}
<div class="container-fluid">
    <div class="row">
            <h2>List of Your Recipes</h2>
    </div>
    <div id="carouselMultiItemExample" class="carousel slide carousel-dark text-center" data-mdb-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container-fluid">
                    <div class="row">
                        {% if recipes %}
                        {% for r in recipes %}
                        <div class="col-lg-3 d-lg-block">
                            <div class="card">
                                <img src="{{ MEDIA_URL }}{{ r.imagePath }}" class="card-img-top img-fluid"
                                    alt="Recipe Image" />
                                <div class="card-body">
                                    <h5 class="card-title">{{ r.name }}</h5>
                                    <p class="card-text">
                                        Description
                                    <div id="{{ r.slug }}">
                                        <div class="stars-outer">
                                            <div class="stars-inner"></div>
                                        </div>
                                        </p>
                                        <a href="{% url 'recipes:show_recipe' r.slug %}" class="btn btn-primary">View</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12" style="height:20px;"></div>
                        </div>
    
                        <script>
                            function getRatings() {
                                const starTotal = 5;
                                var my_rating = "{{ r.rating }}";
                                var my_slug = "{{ r.slug }} "
                                const starPercentage = (my_rating / starTotal) * 100;
                                const starPercentageRounded = `${(Math.round(starPercentage / 10) * 10)}%`;
                                document.querySelector(`#${my_slug} .stars-inner`).style.width = starPercentageRounded;
                            }
                            getRatings();
                        </script>
    
                        {% endfor %}
                        {% else %}
                        <li><strong>There are no recipes present.</strong></li>
                        {% endif %}
    
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

templates/groceries/register.html
{% extends 'rapidrecipes/base.html' %}

{% block content_block %}
<div class="container-fluid my-2">
    <h2>Register</h2>
    <form class="form-signin" role="form" method="post" action="."
    oninput='id_password2.setCustomValidity(id_password.value != id_password2.value ? "Passwords do not match." : "")'>
        {% csrf_token %}


        {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %} 
               <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
               </div>
            {% endfor %}
        {% endfor %}
        {% endif %}
        
        <p>Username*:</p>
        <input type="text" name="username" required_id="id_username" maxlength="150" class="form-control w-25" required autofocus>
        <p>E-mail*:</p>
        <input type="email" name="email" id="id_email" maxlength="254" class="form-control w-25" required>
        <p>Password*:</p>
        <input type="password" name="password" required_id="id_password" class="form-control w-25" required>
        <span id="passwordHelpInline" class="form-text">
            Must be minimum 6 characters.
        </span>
        <p></p>
        <p>Retype password:</p>
        <input type="password" id="id_password2" class="form-control w-25" required>
        <p></p>
    
        <button class="btn btn-lg btn-primary btn-block w-25" type="submit" value="Submit">Register</button>
    </form>

</div>
{% endblock %}

templates/groceries/shoppingList.html
{% extends 'rapidrecipes/base.html' %}
{% block content_block %}

<div class="container-fluid">
    <h2>Add an ingredient</h2>
    <form class="w-25" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label>Select Item</label>
            <select class="form-control select2" name="ingredient" id="ingredient"
                onchange="getRawFoodMeasurementTypes(event)" required>
                <option disabled selected value>Select An Ingredient</option>
                {% for rawFood in rawFoods.all %}
                <option value="{{ rawFood.name }}">{{ rawFood }}</option>
                {% endfor%}
            </select>
        </div>
        <div class="mb-3">
            <label for="quantity" class="form-label">Quantity</label>
            <input type="number" class="form-control" name="ingredientamount" id="ingredientamount" value="0" min="0">
        </div>
        <div class="mb-3">
            <label for="ingredientmeasurement" class="form-label">Measurement</label>
            <select class="form-control select2" name="ingredientmeasurement" id="ingredientmeasurement" required>
                <option disabled selected value>Select A Measurement</option>
            </select>
        </div>
        <div class="form-check" id="owned-radio">
            <input class="form-check-input" type="radio" name="owned" id="owned">
            <label class="form-check-label" for="owned">
                Owned
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="owned" id="notowned" checked>
            <label class="form-check-label" for="owned">
                Not Owned
            </label>
        </div>

        <div class="col-xs-12" style="height:20px;"></div>
        <button type="submit" class="btn btn-primary" onclick="getAddedGroceries()">Add ingredient</button>
    </form>
    <div class="col-xs-12" style="height:10px;"></div>
    <h2>List of ingredients</h2>
    <div class="table-responsive-lg">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Item</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Owned</th>
                    <th scope="col">Delete?</th>
                </tr>
            </thead>
            <tbody class="table_body">
                {% include 'groceries/table_body.html' %}
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.select2').select2({
            theme: 'bootstrap-5'
        });
    });

    function getRawFoodMeasurementTypes(caller) {
        var ingredientInstance = caller.target.parentNode.parentNode.parentNode;
        //console.log('text: '+$(this).find(":selected").not(':disabled').text());
        var $ingredient = $(ingredientInstance).find('#ingredient');
        var $measurement = $(ingredientInstance).find('#ingredientmeasurement');
        //console.log($measurement.text()); // Print out html
        $.ajax({
            type: 'GET',
            url: "{% url 'food:getRawFoodMeasurementTypes' %}",
            data: { "raw-food": $ingredient.find(":selected").not(':disabled').text() },
            success: function (response) {

                $measurement.find('option').not(':disabled').remove();
                $.each(response, function (key, value) {
                    $measurement.append(`<option value="${value}">${value}</option>`);
                });
                $measurement.show();
            },
            error: function (response) {
                console.log(response);
            }
        });
    };

    function getAddedGroceries() {
        var i = encodeURI(document.getElementById("ingredient").value);
        var m = encodeURI(document.getElementById("ingredientmeasurement").value);
        var a = encodeURI(document.getElementById("ingredientamount").value);
        var o = document.getElementById("owned").checked;

        var suffix = `?i=${i}&m=${m}&a=${a}&o=${o}`

        $('.table_body').html('').load(
            "{% url 'groceries:get_added_grocery' %}" + suffix
        );
        
    };

    function deleteGrocery(event) {
        var row = event.target.parentNode.parentNode;

        var id = encodeURI($(row).find("#item-id").text());

        $('.table_body').html('').load(
            "{% url 'groceries:delete_grocery' %}?id=" + id
        );
    };

    function changeAmount(event) {
        var row = event.target.parentNode.parentNode.parentNode.parentNode;

        if (event.key === "Enter") {
           
            var id = $(row).find("#item-id").text();            
            var a = encodeURI($(row).find("#item-amount").val());

            var suffix = `?id=${id}&a=${a}`;
            $('.table_body').html('').load(
                "{% url 'groceries:change_amount' %}" + suffix
            );
            
        };
    };

</script>
{% endblock %}

templates/groceries/table_body.html
{% for item in groceries %}
<tr id="he2y">
    <td hidden>
        <p id="item-id">{{ item.id }}</p>
    </td>
    <td id="item-name">{{ item.rawFood.name }}</td>
    <td>
        <div class="row align-items-center">
            <div class="col-auto">
                <input type="number" name="item-amount" id="item-amount" value="{{ item.amount}}" onkeydown="changeAmount(event)"  min="0" step="0.1"/>
            </div>
            <div class="col-auto">
                <p class="justify-content-centre" id="item-measurement">{{ item.measuredIn.unit }}</p>
            </div>
        </div>
    </td>
    <td id="owned">
        {% if item.available %}
        ✔️
        {% else %}
        ❌
        {% endif %}
    </td>
    <td>
        <button type="button" class="btn btn-danger" onclick="deleteGrocery(event)">Delete</button>
    </td>
</tr>
{% endfor%}