food/urls.py
from django.urls import path
from food import views
from recipes.views import index as recipe_index

app_name = 'food'
urlpatterns = [
    path('', recipe_index, name='index'),
    path('ajax/get/getRawFoodMeasurementTypes', views.getRawFoodMeasurementTypes, name="getRawFoodMeasurementTypes")
]

groceries/urls.py
from django.urls import path
from groceries import views
from recipes.views import index as recipe_index

app_name = 'groceries'
urlpatterns = [
    path('', recipe_index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('shoppinglist/', views.shopping_list, name='shoppinglist'),
    path('get_added_grocery/', views.get_added_grocery, name="get_added_grocery"),
    path('delete_grocery/', views.delete_grocery, name="delete_grocery"),
    path('change_amount/', views.change_amount, name="change_amount"),
    path('save_recipe', views.save_recipe, name="save_recipe"),
    path('recipelist/', views.recipes_list, name="recipe_list"),
]

rapid_recipes/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipes import views
from django.conf import settings
from django.conf.urls.static import static

#app_name='rapid'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('recipes/', include('recipes.urls')),

    path('food/', include('food.urls')),
    path('groceries/', include('groceries.urls')),
    path('about/', views.about, name='about'), 
    path('contact/', views.contact, name='contact'),
    path('contact/success', views.success, name='success'), 


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('<slug:recipe_name_slug>/', views.show_recipe, name='show_recipe'),
    path('search', views.search, name='search'),
]

recipes/models.py
from django.db import models
from django.template.defaultfilters import slugify
from food.models import RawFood, Measurement
from django.contrib.auth.models import User


class Category(models.Model):
    CATEGORY_MAX_LENGTH = 255
    TEXT_MAX_LENGTH = 255
    
    category = models.CharField(max_length=CATEGORY_MAX_LENGTH, unique=True)
    description = models.CharField(max_length=TEXT_MAX_LENGTH, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category


class Recipe(models.Model):

    NAME_MAX_LENGTH = 255
    IMAGE_PATH_MAX_LENGTH = 255
    RATING_MAX_SIZE = 5
    DIFFICULTY_MAX_SIZE = 5

    name = models.CharField(max_length=NAME_MAX_LENGTH)
    category = models.ManyToManyField(Category, blank=True)
    rating = models.FloatField(max_length=RATING_MAX_SIZE, default=0)
    imagePath = models.CharField(max_length=IMAGE_PATH_MAX_LENGTH, blank=True)
    difficulty = models.FloatField(max_length=DIFFICULTY_MAX_SIZE, default=0)
    users = models.ManyToManyField(User, blank=True)
    time = models.FloatField(default = 0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Recipe, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Ingredient(models.Model):

    AMOUNT_MAX_LENGTH = 50

    rawFood = models.ForeignKey(RawFood, on_delete=models.CASCADE) # If a raw food is deleted, delete ingredient
    amount = models.CharField(max_length=AMOUNT_MAX_LENGTH)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE) # Ingredient belongs to a recipe
    measuredIn = models.ForeignKey(Measurement, on_delete=models.CASCADE)
    def __str__(self):
        return self.rawFood.name


class Instruction(models.Model):
    MEDIA_PATH_MAX_LENGTH = 255

    step = models.SmallIntegerField()
    description = models.TextField()
    media = models.CharField(max_length=MEDIA_PATH_MAX_LENGTH, blank=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE) # Instruction belongs to a recipe
    def __str__(self):
        return str(self.step)

recipes/forms.py
from pickletools import read_uint1
from django import forms
from django.db import models
from django.contrib.auth.models import User
from recipes.models import Instruction, Recipe, Ingredient, Category

class ContactForm(forms.Form):
    firstname = forms.CharField(required=True)
    lastname = forms.CharField(required=True)
    phonenumber = forms.CharField(required=False)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

class FilterForm(forms.Form):
    lunch = forms.BooleanField(label='lunch', required=False)
    dinner = forms.BooleanField(label='dinner', required=False)
    breakfast = forms.BooleanField(label='breakfast', required=False)
    easy = forms.BooleanField(label='easy', required=False)
    medium = forms.BooleanField(label='medium', required=False)
    hard = forms.BooleanField(label='hard', required=False)
    drink = forms.BooleanField(label='drink', required=False)
    vegan = forms.BooleanField(label='vegan', required=False)
    vegetarian = forms.BooleanField(label='vegetarian', required=False)
    beef = forms.BooleanField(label='beef', required=False)
    chicken = forms.BooleanField(label='chicken', required=False)
    fish = forms.BooleanField(label='fish', required=False)
    
    

recipes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from recipes.models import Category, Recipe, Ingredient, Instruction
from food.models import RawFood, Measurement
from recipes.forms import ContactForm, FilterForm
from django.core.mail import send_mail, BadHeaderError
from rapid_recipes.settings import DEFAULT_FROM_EMAIL
from django.core.files.storage import default_storage


# Create your views here.

def index(request):
    a = 0
    if request.method == 'GET':
        form = FilterForm()
        context_dict = {}
        recipe_list = Recipe.objects.order_by('-rating')
        context_dict = {'recipes': recipe_list, 'form':form}
    elif request.method == 'POST':
        context_dict = {}
        form = FilterForm(request.POST)

        categories = []
        for key, value in form.data.items():
            if key == 'csrfmiddlewaretoken':
                continue
            else:
                categories.append(key)

        if categories:
            recipe_list = Recipe.objects

            for category in categories:
                c = Category.objects.get(category=category)
                recipe_list = recipe_list.filter(category=c)
            
            recipe_list = recipe_list.order_by('-rating')
        else:
            recipe_list = Recipe.objects.order_by('-rating')
        
        context_dict = {'recipes': recipe_list, 'form':form}
    return render(request, "recipes/index.html", context_dict)

def about(request):
    response = render(request, 'recipes/about.html')
    return response

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            email = form.cleaned_data['email']
            phonenumber = form.cleaned_data['phonenumber']
            message = form.cleaned_data['message']

            message_with_user_info = "Name: " + lastname + ", " + firstname + "\n" + "Email: " + email + "\n"
            if phonenumber:
                message_with_user_info += "Phonenumber: " + phonenumber + "\n"
            
            message_with_user_info += message

            try:
                send_mail("Inquiry from User", message_with_user_info, DEFAULT_FROM_EMAIL, [DEFAULT_FROM_EMAIL])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('index')
    return render(request, "recipes/contact.html", {'form': form})

def success(request):
    return HttpResponse("The email was successfully sent!")
    
def show_recipe(request, recipe_name_slug):
    context_dict = {}
    try:
        recipe = Recipe.objects.get(slug=recipe_name_slug)
        recommended_recipes = Recipe.objects.order_by('-rating').exclude(id=recipe.id)[:5]
        ingredients = recipe.ingredient_set.all()
        instructions = recipe.instruction_set.all()
        
        context_dict['recipe'] = recipe
        context_dict['ingredients'] = ingredients
        context_dict['instructions'] = instructions
        context_dict['recommended_recipes'] = recommended_recipes
        
    except Recipe.DoesNotExist:
        context_dict['recipe'] = None

    return render(request, 'recipes/view_recipe.html', context_dict)

def add_recipe(request):
    if request.method == "GET":
        categories = Category.objects.all()
        rawFoods = RawFood.objects.all()

        context_dict = {
            "categories" : categories,
            "rawFoods" : rawFoods,
            }
        return render(request, 'recipes/add_recipe.html', context_dict)
    else:
    
        # Handle Post
        post = request.POST
        name = post['recipename']
        time = post['time']
        rating = post['rating']
        difficulty = post['difficulty']

        # Get categories as list
        categories = post.getlist("categories")

        # Get ingredients, their amounts and measurements as a list
        ingredients = post.getlist("ingredient")
        ingredientamounts = post.getlist("ingredientamount")
        ingredientmeasurements = post.getlist("ingredientmeasurement")

        # Get instructions as a list
        instructions = post.getlist("instruction")
        
        files = request.FILES

        instructionimages = []
        for i in range(len(instructions)):
            try:
                imagename = f"instructionimage{i+1}"
                image = files[imagename]
                instructionimages.append(image)
            except:
                instructionimages.append(None)
        

        recipeimage = files['recipeimage']
        suffix = recipeimage.name.rsplit(".", 1)[-1]

        recipeimagepath = f"recipes/{name}/{name}.{suffix}"
        default_storage.save(f"{recipeimagepath}", recipeimage)


        instructionimagepaths = []
        for (i, ii) in enumerate(instructionimages):
            if ii != None:
                suffix = ii.name.rsplit(".", 1)[-1]

                instructionimagepath = f"recipes/{name}/instructions/instruction{i}.{suffix}"
                default_storage.save(f"{instructionimagepath}", ii)
                instructionimagepaths.append(instructionimagepath)
            else:
                instructionimagepaths.append(None)

        # categories
        recipe = Recipe.objects.get_or_create(name=name,
                        rating=rating,
                        difficulty=difficulty,
                        time=time,
                        imagePath = recipeimagepath)[0]
        recipe.save()

        for category in categories:
            c = Category.objects.get(category=category)
            recipe.category.add(c)
        
        
        
        for (i, ia, im) in zip(ingredients, ingredientamounts, ingredientmeasurements):
            m = Measurement.objects.get(unit=im)
            f = RawFood.objects.get(name=i)
            ingredient = Ingredient.objects.get_or_create(amount=ia,
                                                            rawFood=f, 
                                                            recipe=recipe,
                                                            measuredIn=m)[0]
            ingredient.save()


        for i in range(len(instructions)):
            if instructionimages[i] != None:
                instruction = Instruction.objects.get_or_create(step=i+1,
                                                                description=instructions[i],
                                                                media=instructionimagepaths[i],
                                                                recipe=recipe)[0]
            else:
                instruction = Instruction.objects.get_or_create(step=i+1,
                                                                description=instructions[i],
                                                                recipe=recipe)[0]
            instruction.save()

        return redirect('index')
    

def search(request):
    if request.method == "POST":
        search = request.POST['search']
        recipes = Recipe.objects.filter(name__icontains=search)
        a = 0
        context_dict = {'search':search, 'recipes':recipes}
        response = render(request, 'recipes/search.html', context_dict)
        return response
    if request.method == 'GET':
        return redirect('index')

templates/recipes/about.html
{% extends 'rapidrecipes/base.html' %}
{% block content_block %}

<div class="container-fluid">
    <h2>About</h2>
    <p>We are a team of young and talented programmers that will not sell their souls to corporate.*</p>
    <div class="hidden-text">
        <p><small>Yet*</small></p>
    </div>
</div>
{% endblock %}

templates/recipes/add_recipe.html
{% extends 'rapidrecipes/base.html' %}
{% block content_block %}

<div class="container-fluid">
    <h2>Add A Recipe</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <div class="mb-3">
                <label for="recipename" class="form-label">Recipe Name</label>
                <input type="text" class="form-control" id="recipename" name="recipename" placeholder="Untitled"
                    required>
            </div>
            <div class="container border border-dark rounded mb-3" id="recipeImageContainer" style="display: none;">
                <img id="recipeimageoutput" class="rounded mx-auto d-block" style="max-width: 100%;" />
            </div>
            <div class="custom-file mb-3">
                <label for="recipeimage" class="custom-file-label">Add Recipe Image</label>
                <input type="file" class="custom-file-input" name="recipeimage" oninput="addRecipeImage(event)" accept="image/*" required>
            </div>
            <div class="mb-3">
                <label for="time" class="form-label">Preperation Time (in minutes)</label>
                <input type="number" class="form-control" id="time" name="time"  min="0" value="0">
            </div>
            <div class="mb-3">
                <label for="rating" class="form-label">Rating (between 0 to 5)</label>
                <input type="number" class="form-control" id="rating" name="rating" min="0" max="5" step="0.1"
                    value="0">
            </div>
            <div class="mb-3">
                <label for="difficulty" class="form-label">Difficulty (between 0 to 5)</label>
                <input type="number" class="form-control" id="difficulty" name="difficulty" min="0" max="5" step="0.1"
                    value="0">
            </div>
            <div class="row row-cols-4 mb-3 mx-1">
                {% for category in categories %}
                <div class="form-check col-md-3 my-1">
                    <input class="form-check-input" type="checkbox" value="{{ category }}" id="{{ category }}"
                        name="categories">
                    <label class="form-check-label" for="{{ category }}">
                        {{ category }}
                    </label>
                </div>
                {% endfor %}
            </div>
        </div>
        <div>
            <h3>Add Ingredients to Your Recipe</h3>
            <div id="ingredientforms">
                <div class="ingredientform" id = "ingredientform">
                    <div class="form-row mb-3">
                        <div class="col">
                            <label for="ingredient" class="form-label">Choose Ingredient</label>
                            <select class="form-control" name="ingredient" id="ingredient" onchange="getRawFoodMeasurementTypes(event)" required>
                                <option disabled selected value>Select An Ingredient</option>
                                {% for rawFood in rawFoods.all %}
                                <option value="{{ rawFood }}">{{ rawFood }}</option>
                                {% endfor%}
                            </select>
                        </div>
                        <div class="col">
                            <label for="ingredientamount" class="form-label">Ingredient Amount</label>
                            <input type="number" class="form-control" name="ingredientamount" id="ingredientamount" value="0" min="0">
                        </div>
                        <div class="col">
                            <label for="ingredientmeasurement" class="form-label">Measurement</label>
                            <select class="form-control" name="ingredientmeasurement" id="ingredientmeasurement" required>
                                <option disabled selected value>Select A Measurement</option>
                            </select>
                        </div>
                        <div class="col-auto align-self-end">
                            <button class="btn btn-danger" type="button" onclick="deleteIngredient()">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-success btn-block mb-3" onclick="addIngredient()" type="button">
                Add Another Ingredient
            </button>
        </div>
        <div>
            <h3>Add Instructions to Your Recipe</h3>
            <div id="instructionforms">
                <div id="instructionform">
                    <div class="mb-3">
                        <textarea class="form-control" rows="10" placeholder="Add Description Here"
                            name="instruction" id="instruction"></textarea>
                    </div>
                    <div class="form-row mb-3 mx-0">
                        <div class="col custom-file">
                            <label for="instructionimage" class="custom-file-label" id="instructionimagelabel">Add Instruction Image</label>
                            <input type="file" class="custom-file-input" name="instructionimage" id="instructionimage" accept="image/*"
                                onchange="instructionImageAdded(event)">
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-danger" type="button" onclick="deleteInstruction()">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-success btn-block mb-3" onclick="addInstruction()" type="button">
                Add Another Instruction
            </button>
        </div>
        <button class="btn btn-primary mb-5" type="submit" onsubmit="alert('You have successfully added a new recipe.')">Submit</button>
    </form>
</div>
<script>

    function getRawFoodMeasurementTypes(caller) {
            var ingredientInstance = caller.target.parentNode.parentNode.parentNode;
            //console.log('text: '+$(this).find(":selected").not(':disabled').text());
            var $ingredient = $(ingredientInstance).find('#ingredient');
            var $measurement = $(ingredientInstance).find('#ingredientmeasurement');
            //console.log($measurement.text()); // Print out html
            $.ajax({
                type: 'GET',
                url: "{% url 'food:getRawFoodMeasurementTypes' %}",
                data: {"raw-food": $ingredient.find(":selected").not(':disabled').text()},
                success: function (response){

                    $measurement.find('option').not(':disabled').remove();
                    $.each(response, function(key,value){
                        $measurement.append(`<option value="${value}">${value}</option>`);
                    });
                    $measurement.show();
                },
                error: function (response){
                    console.log(response);
                }
            });
    };

    $(document).ready(function() {
        $('.select2').select2({
            theme: 'bootstrap-5',
        });
    });

    var addRecipeImage = function (event) {
        var imageContainer = document.getElementById('recipeImageContainer');
        imageContainer.style.display = 'block';
        var image = document.getElementById('recipeimageoutput');
        image.src = URL.createObjectURL(event.target.files[0]);
    };


    var addIngredient = function () {
        var ingredientform = document.getElementById('ingredientform');
        var clone = ingredientform.cloneNode(true);
    
        document.getElementById('ingredientforms').appendChild(clone);
        $(clone).find('#ingredient').val("");
        $(clone).find('#ingredientamount').val(0);
        $(clone).find('#ingredientmeasurement').find('option').not(":disabled").remove();
    };

    var deleteIngredient = function () {
        var ingredientforms = document.getElementById('ingredientforms');
        var ingredientformtodelete = event.target.parentNode.parentNode.parentNode;

        if (ingredientforms.children.length == 1) {
            alert("You have to have at least one ingredient in your recipe.");
        } else {
            ingredientformtodelete.remove();
        }
    };

    var instructionImageAdded = function (event) {
        alert("You successfully added an instruction image!")

        var element = event.target;
        var label = element.parentNode.children[0];
        label.innerHTML = "Change Instruction Image";
        label.style.backgroundColor = "lightgreen";
    };

    var addInstruction = function () {
        var instructionform = document.getElementById('instructionform');
        var instructionforms = instructionform.parentNode;
        var clone = instructionform.cloneNode(true);

        
        document.getElementById('instructionforms').appendChild(clone);
        
        var instructions = instructionforms.children.length;

        for (var i = 1; i <= instructions; i++) {
            var hello = instructionforms.children[i-1].children[1].children[0].children[1];
            hello.name = "instructionimage" + i;
        }

        $(clone).find('#instruction').val("");
        var imagelabel = $(clone).find('#instructionimagelabel');
        imagelabel.css("background-color", "initial");
        imagelabel.html("Add Instruction Image");
    };

    var deleteInstruction = function () {
            var instructionforms = document.getElementById('instructionforms');
            var instructionformtodelete = event.target.parentNode.parentNode.parentNode;

            if (instructionforms.children.length == 1) {
                alert("You have to have at least one instruction in your recipe.");
            } else {
                instructionformtodelete.remove();

                var instructions = instructionforms.children.length;

                for (var i = 1; i <= instructions; i++) {
                    var instructionimage = instructionforms.children[i - 1].children[1].children[0].children[1];
                    instructionimage.name = "instructionimage" + i;
                }

            }
    };

</script>
{% endblock %}

templates/recipes/contact.html
{% extends 'rapidrecipes/base.html' %}
{% block content_block %}
{% load crispy_forms_tags %}
<div class="container-fluid">
    <h2>Contact</h2>
    <div class="container-fluid">
        <p>
            <strong>Email:</strong> 2538359C@student.gla.ac.uk <br />
            <strong>Phone Number:</strong> (+44) 123123412345
        </p>
        <p class="h3">Glasgow Office</p>
        <p>
            Boyd Orr Building<br />
            University Avenue<br />
            Glasgow, G12 8QW<br />
            United Kingdom
        </p>
    </div>
    <div class="container-fluid mt-5">
        <p class="h2">Message Us</p>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors}}
            <div class="row align-items-start mb-3">
                <div class="col">
                    {{ form.firstname.errors }}
                    {{ form.firstname | as_crispy_field }}
                </div>
                <div class="col">
                    {{ form.lastname.errors}}
                    {{ form.lastname | as_crispy_field }}
                </div>
            </div>
            <div class="row align-items-start mb-3">
                <div class="col">
                    {{ form.email.errors }}
                    {{ form.email | as_crispy_field }}
                </div>
                <div class="col">
                    {{ form.phonenumber.errors }}
                    {{ form.phonenumber | as_crispy_field }}
                </div>
            </div>
            <div class="mb-3">
                {{ form.message.errors }}
                {{ form.message | as_crispy_field }}
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/recipes/search.html
<!DOCTYPE html>
{% extends 'rapidrecipes/base.html' %}
{% load staticfiles %}
{% block content_block %}

{% if recipes %}
<div id="carouselMultiItemExample" class="carousel slide carousel-dark text-center" data-mdb-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container-fluid">
                <div class="row">
                    {% for r in recipes %}
                    <div class="col-lg-3 d-lg-block">
                        <div class="card">
                            <img src="{{ MEDIA_URL }}{{ r.imagePath }}" class="card-img-top img-fluid" alt="Recipe Image"/>
                            <div class="card-body">
                                <h5 class="card-title">{{ r.name }}</h5>
                                <p class="card-text">
                                    Description
                                <div id="{{ r.slug }}">
                                    <div class="stars-outer">
                                        <div class="stars-inner"></div>
                                    </div>
                                    </p>
                                    <a href="{% url 'recipes:show_recipe' r.slug %}"class="btn btn-primary">View</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12" style="height:20px;"></div>
                    </div>
              
                    <script>
                        function getRatings() {
                            const starTotal = 5;
                            var my_rating = "{{ r.rating }}";
                            var my_slug = "{{ r.slug }} "
                            const starPercentage = ( my_rating / starTotal) * 100;
                            const starPercentageRounded = `${(Math.round(starPercentage / 10) * 10)}%`;
                            document.querySelector(`#${my_slug} .stars-inner`).style.width = starPercentageRounded;
                        }
                        getRatings();
                    </script>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<ul>
    <li><strong>There are no recipes present.</strong></li>
    <li><a href="https://www.google.co.uk/search?q={{ search }}">Search on google<a /></li>
</ul>
{% endif %}
{% endblock %}

templates/recipes/view_recipe.html
{% extends 'rapidrecipes/base.html' %}
{% load staticfiles %}
{% block content_block %}

<div class="container-fluid my-2">
    {% if recipe %}
    <div class="row mb-3">
        <script src="{% static 'javascript/viewRecipe.js' %}"></script>
        <div class="col">
            <h2>{{ recipe.name }}</h2>
        </div>
        {% if user.is_authenticated %}
        <div class="col-auto">
            <button class="btn btn-success" onclick="save()">Save</button>
        </div>
        {% endif%}
    </div>
    <div class="row">
        <div class="col-md-5">
            <img src="{{ MEDIA_URL }}{{ recipe.imagePath }}" class="card-img-top" alt="Image" width="30%" />
            <div class="col-xs-12" style="height: 15px"></div>
            <h4>Instructions:</h4>
            <p class="fs-1">
                {% for instruction in instructions %}
                {% if instruction.media %}
                <img src="{{ MEDIA_URL }}{{ instruction.media }}" alt="Image" class="img-fluid" />
                {% endif %}
                <strong>{{ instruction.step }}. </strong>{{ instruction.description }}<br>
                {% endfor %}
            </p>
        </div>

        <div class="col-md-4">
            <strong>
                Preparation time:
            </strong>
            <br>
            {{ recipe.time | floatformat }} min
            <br>
            <br>
            <strong>Rating: <br></strong>
            <!--stars-->
            <div id="{{ recipe.slug }}-rating">
                <div class="stars-outer">
                    <div class="stars-inner"></div>
                </div>
            </div> <br>
            <br>
            <strong>Difficulty: <br></strong>
            <!--stars-->
            <div id="{{ recipe.slug }}-difficulty">
                <div class="stars-outer">
                    <div class="stars-inner"></div>
                </div>
            </div> <br>
            <br>
            <strong>Ingredients: <br></strong>
            <div class="list-group">
                <p>
                    {% for ingredient in ingredients %}
                    &#9642; {{ ingredient.rawFood.name }} - {{ ingredient.amount }} {{ ingredient.measuredIn }}.<br>
                    {% endfor %}
                </p>
            </div>
        </div>
        <script>
        getRatings('{{ recipe.slug }}', '{{ recipe.rating }}', '{{ recipe.difficulty }}');
        
        function save() {
                var id = "{{ recipe.id }}";

                $.ajax({
                    type: 'GET',
                    url: "{% url 'groceries:save_recipe' %}",
                    data: { "recipe_id": id }
                });
        };
        </script>
        <div class="col-md-3 text-center">
            <h4>Recommended recipes</h4>
            {% for recipe in recommended_recipes %}
            <a href="{% url 'recipes:show_recipe' recipe.slug %}">
                <div class="mb-4">
                    <h5 class="text-center">{{recipe.name}}</h5>
                    <img src="{{ MEDIA_URL }}{{ recipe.imagePath }}" class="card-img-top w-75" alt="Image" />
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}